### ISSUE TITLE
Make token tree available

### ISSUE THREAD

**Issue by djzwerg** [backdrop-contrib/pack_upload#2]
Tokens are still working! But the tree is still missing.

**Comment by ghost** [comment]
See if this helps: https://api.backdropcms.org/api/backdrop/core%21modules%21system%21system.theme.inc/function/theme_token_tree/1

Check out some of the other core modules listed on that page who also use that theme function. Their example might help you.

**Comment by djzwerg** [comment]
@BWPanda thanks!

Solved in https://github.com/djzwerg/pack_upload/commit/b21ef05467eeff6003e08bc9aa711d6af52ca41f.
