### ISSUE TITLE
Delete archives after extracting

### ISSUE THREAD

**Issue by djzwerg** [backdrop-contrib/pack_upload#3]

**Comment by ghost** [comment]
Drush uses:
```php
exec(
  "rm backdrop.zip"
);
```
So maybe you can do something similar...?

https://github.com/backdrop-contrib/backdrop-drush-extension/blob/0686452b800394c8cf0f800730b6949da952adb6/commands/pm/download_backdrop.drush.inc#L116

**Comment by herbdool** [comment]
Maybe looking in the file tests in core could provide a clue. If you are using straight PHP perhaps `unlink()` is what you need.

**Comment by djzwerg** [comment]
Thanks! @herbdool this was what I needed. Solved with https://github.com/djzwerg/pack_upload/commit/c50e7e6d59cbf28a1c27b6eed80f9721681fd38f.
