### ISSUE TITLE
Who is the maintainer of this module?

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/pack_upload#4]
No one is listed as the maintainer of the module. @djzwerg is listed as the person that ported the module and I presume is also the maintainer, but I think the maintainer should be listed separately. 

The new project checklist includes this:

 Include a README.md file that includes license and maintainer information. You can use [this example](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md).

Thanks for porting this module!

I believe it is our goal is to make sure that someone is listed as the maintainer of every module.

**Comment by djzwerg** [comment]
Thanks @stpaultim for this hint. I've added that part with https://github.com/backdrop-contrib/pack_upload/commit/3c12a858b8a54024612d74c87ee0a634491ecb1e.

I've asked at https://www.drupal.org/project/pack_upload/issues/3189907 whether the current Drupal maintainers want to maintain the Backdrop version. Looking forward to a response at that issue.

**Comment by stpaultim** [comment]
@djzwerg - You are not officially listed as the maintainer of this module. Is that intentional?

If you are not interested, may I take over maintainership of this module? Would you like to co-maintain this module?

**Comment by stpaultim** [comment]
@djzwerg - Thanks!

**Comment by stpaultim** [comment]
@djzwerg - Are you also able to give me admin permissions?

**Comment by djzwerg** [comment]
@stpaultim thanks a lot! Having you as the maintainer would be very great!

For now I do not have enough time to maintain modules

**Comment by djzwerg** [comment]
> @djzwerg - Are you also able to give me admin permissions?

Yes, of course. I have to figure out how to do this.

**Comment by stpaultim** [comment]
@djzwerg - I think it's here:

![image](https://user-images.githubusercontent.com/3144571/177253254-65c700f6-498a-417d-b7b2-e54d8d412962.png)

**Comment by stpaultim** [comment]
@djzwerg - THis is screenshot from another project I maintain, but truthfully I'm not 100% certain if this is correct.

**Comment by djzwerg** [comment]
Congrats @stpaultim you are now the maintainer 🤗
